#!/usr/bin/env bash
# scripts/record-cassettes.sh
#
# Re-record every Phase-2 test cassette from the live upstream source.
# See docs/conventions/cassette-recording.md + .cursor/rules/real-data-tests.mdc.
#
# Each adapter has exactly one cassette file; after recording, the
# matching SOURCE.md sibling is regenerated with the capture URL, UTC
# capture date, and SHA-256 of the bytes on disk.
#
# Run from repo root:
#   make record-cassettes
#
# Requires: uv, network access to knesset.gov.il and production.oknesset.org.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

FIX="tests/fixtures/phase2/cassettes"
LOOKUPS="tests/fixtures/phase2/lookups"
NOW="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

record() {
  local adapter="$1" url="$2" ext="$3"
  shift 3
  local out="$FIX/$adapter/sample.$ext"
  local source_md="$FIX/$adapter/SOURCE.md"

  mkdir -p "$(dirname "$out")"

  # Use --out to write bytes; forward remaining args (e.g. --max-lines).
  uv run python -m civic_archival fetch \
    --url "$url" \
    --out "$out" \
    "$@" \
    >"/tmp/record_${adapter}.json"

  local sha
  sha="$(python3 -c "import hashlib,sys; print(hashlib.sha256(open('$out','rb').read()).hexdigest())")"

  {
    echo "# Cassette provenance — $adapter"
    echo ""
    echo "- **Upstream URL**: \`$url\`"
    echo "- **Captured (UTC)**: $NOW"
    echo "- **File**: \`$out\`"
    echo "- **SHA-256**: \`$sha\`"
    if [ "$#" -gt 0 ]; then
      echo "- **Recorder flags**: \`$*\`"
    fi
    echo ""
    echo "Regenerated by \`make record-cassettes\`. See"
    echo "\`.cursor/rules/real-data-tests.mdc\` for the policy."
  } >"$source_md"

  echo "  recorded $adapter -> $out ($(wc -c <"$out") bytes, sha=${sha:0:12}…)"
}

echo "Recording Phase-2 cassettes @ $NOW"

# People: KNS_Person — ALL historical MKs (ordered by PersonID), top 500.
# Dropped the `IsCurrent eq true` filter so the Person dimension covers
# historical Knessets; this lets the votes adapter's stub Persons be
# back-filled by a subsequent people run (votes cassette is Knesset 16
# MKs, e.g. PersonID=405 Benjamin Elon, which `IsCurrent eq true` would
# have excluded). `$orderby=PersonID` keeps the first-row pin stable
# across re-records.
record people \
  'https://knesset.gov.il/Odata/ParliamentInfo.svc/KNS_Person?$format=json&$orderby=PersonID&$top=500' \
  json

# Committees: KNS_Committee — Knesset 25, top 20.
record committees \
  'https://knesset.gov.il/Odata/ParliamentInfo.svc/KNS_Committee?$format=json&$filter=KnessetNum eq 25&$top=20' \
  json

# Sponsorships: KNS_Bill — Knesset 25, top 20.
record sponsorships \
  'https://knesset.gov.il/Odata/ParliamentInfo.svc/KNS_Bill?$format=json&$filter=KnessetNum eq 25&$top=20' \
  json

# Votes: oknesset pipelines CSV of per-MK votes (one row per
# (vote_id, kmmbr_id, vote_result)). The full CSV is ~85 MB so we
# capture the first 100 rows verbatim — real upstream bytes, just
# truncated to a size we can commit.
record votes \
  'https://production.oknesset.org/pipelines/data/votes/vote_rslts_kmmbr_shadow/vote_rslts_kmmbr_shadow.csv' \
  csv \
  --max-lines 101

# Attendance (Phase-2.5 Tier-2 downgrade): the Knesset OData does not
# expose per-MK session attendance. The oknesset meeting-attendees
# mirror republishes KNS_CommitteeSession enriched with
# attended_mk_individual_ids (array) parsed from the session protocol.
# First 50 rows is enough to cover both empty ([]) and populated arrays.
record attendance \
  'https://production.oknesset.org/pipelines/data/people/committees/meeting-attendees/kns_committeesession.csv' \
  csv \
  --max-lines 51

# Positions (Phase-2.5): KNS_PersonToPosition, Tier-1 OData. Knesset 25
# slice (100 rows). Declares CommitteeID but 0 rows are populated in
# practice, so the adapter emits party + office edges only.
record positions \
  'https://knesset.gov.il/Odata/ParliamentInfo.svc/KNS_PersonToPosition?$format=json&$filter=KnessetNum eq 25&$orderby=PersonToPositionID&$top=200' \
  json

# Bill initiators (Phase-2.5): KNS_BillInitiator, Tier-1 OData. No
# KnessetNum column (filter yields 400) — we record the most recent
# 100 rows DESC by BillInitiatorID to cover live Knesset 25 bills.
record bill_initiators \
  'https://knesset.gov.il/Odata/ParliamentInfo.svc/KNS_BillInitiator?$format=json&$orderby=BillInitiatorID desc&$top=100' \
  json

# Committee memberships (Phase-2.5): oknesset mk_individual_committees.csv.
# KNS_PersonToPosition's CommitteeID is 100% NULL in practice, so
# committee memberships have to come from the oknesset mirror. Keyed
# by mk_individual_id (not PersonID) — see the mk_individual lookup
# below.
record committee_memberships \
  'https://production.oknesset.org/pipelines/data/members/mk_individual/mk_individual_committees.csv' \
  csv \
  --max-lines 101

# Shared mk_individual lookup (Phase-2.5): NOT an adapter source — a
# dimension table used by attendance and committee_memberships to
# resolve mk_individual_id → PersonID. Lives under lookups/ instead
# of cassettes/ because it's consumed, not ingested.
MK_OUT="$LOOKUPS/mk_individual/sample.csv"
MK_URL='https://production.oknesset.org/pipelines/data/members/mk_individual/mk_individual.csv'
mkdir -p "$(dirname "$MK_OUT")"
uv run python -m civic_archival fetch \
  --url "$MK_URL" \
  --out "$MK_OUT" \
  >"/tmp/record_mk_individual.json"
mk_sha="$(python3 -c "import hashlib; print(hashlib.sha256(open('$MK_OUT','rb').read()).hexdigest())")"
{
  echo "# Lookup provenance — mk_individual"
  echo ""
  echo "- **Upstream URL**: \`$MK_URL\`"
  echo "- **Captured (UTC)**: $NOW"
  echo "- **File**: \`$MK_OUT\`"
  echo "- **SHA-256**: \`$mk_sha\`"
  echo ""
  echo "Regenerated by \`make record-cassettes\`. See"
  echo "\`.cursor/rules/real-data-tests.mdc\` for the policy."
} >"$LOOKUPS/mk_individual/SOURCE.md"
echo "  recorded mk_individual lookup -> $MK_OUT ($(wc -c <"$MK_OUT") bytes, sha=${mk_sha:0:12}…)"

echo "Done. Review new cassettes + SOURCE.md files and commit together."
