#!/usr/bin/env bash
# scripts/record-cassettes.sh
#
# Re-record every Phase-2 test cassette from the live upstream source.
# See docs/conventions/cassette-recording.md + .cursor/rules/real-data-tests.mdc.
#
# Each adapter has exactly one cassette file; after recording, the
# matching SOURCE.md sibling is regenerated with the capture URL, UTC
# capture date, and SHA-256 of the bytes on disk.
#
# Run from repo root:
#   make record-cassettes
#
# Requires: uv, network access to knesset.gov.il and production.oknesset.org.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

FIX="tests/fixtures/phase2/cassettes"
NOW="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

record() {
  local adapter="$1" url="$2" ext="$3"
  shift 3
  local out="$FIX/$adapter/sample.$ext"
  local source_md="$FIX/$adapter/SOURCE.md"

  mkdir -p "$(dirname "$out")"

  # Use --out to write bytes; forward remaining args (e.g. --max-lines).
  uv run python -m civic_archival fetch \
    --url "$url" \
    --out "$out" \
    "$@" \
    >"/tmp/record_${adapter}.json"

  local sha
  sha="$(python3 -c "import hashlib,sys; print(hashlib.sha256(open('$out','rb').read()).hexdigest())")"

  {
    echo "# Cassette provenance — $adapter"
    echo ""
    echo "- **Upstream URL**: \`$url\`"
    echo "- **Captured (UTC)**: $NOW"
    echo "- **File**: \`$out\`"
    echo "- **SHA-256**: \`$sha\`"
    if [ "$#" -gt 0 ]; then
      echo "- **Recorder flags**: \`$*\`"
    fi
    echo ""
    echo "Regenerated by \`make record-cassettes\`. See"
    echo "\`.cursor/rules/real-data-tests.mdc\` for the policy."
  } >"$source_md"

  echo "  recorded $adapter -> $out ($(wc -c <"$out") bytes, sha=${sha:0:12}…)"
}

echo "Recording Phase-2 cassettes @ $NOW"

# People: KNS_Person — current Knesset members only, top 50.
record people \
  'https://knesset.gov.il/Odata/ParliamentInfo.svc/KNS_Person?$format=json&$filter=IsCurrent eq true&$top=50' \
  json

# Committees: KNS_Committee — Knesset 25, top 20.
record committees \
  'https://knesset.gov.il/Odata/ParliamentInfo.svc/KNS_Committee?$format=json&$filter=KnessetNum eq 25&$top=20' \
  json

# Sponsorships: KNS_Bill — Knesset 25, top 20.
record sponsorships \
  'https://knesset.gov.il/Odata/ParliamentInfo.svc/KNS_Bill?$format=json&$filter=KnessetNum eq 25&$top=20' \
  json

# Votes: oknesset pipelines CSV of per-MK votes (one row per
# (vote_id, kmmbr_id, vote_result)). The full CSV is ~85 MB so we
# capture the first 100 rows verbatim — real upstream bytes, just
# truncated to a size we can commit.
record votes \
  'https://production.oknesset.org/pipelines/data/votes/vote_rslts_kmmbr_shadow/vote_rslts_kmmbr_shadow.csv' \
  csv \
  --max-lines 101

# Attendance: real Knesset committee sessions (occurrence = attendance event).
# The publicly-accessible OData does not expose per-MK session attendance
# (that only exists on the bot-protected old endpoint); Phase-3 fills in
# attendees by parsing committee protocols. Here we ingest the real
# sessions, which is enough to prove the AttendanceEvent pipeline shape.
record attendance \
  'https://knesset.gov.il/Odata/ParliamentInfo.svc/KNS_CommitteeSession?$format=json&$filter=KnessetNum eq 25&$top=20' \
  json

echo "Done. Review new cassettes + SOURCE.md files and commit together."
